service: ocr-backend-service
runtime: nodejs20
env: standard
network:
  name: default

env_variables:
  APP_ENV: "prod"
  PROJECT_ID: "ocr-dev-440305"
  GOOGLE_CLOUD_PROJECT_ID: "ocr-dev-440305"
  TZ: IST
  NODE_OPTIONS: ""
